# Generated by Django 4.2.7 on 2023-11-23 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 13, 32, 13, 593187, tzinfo=datetime.timezone.utc), verbose_name='Дата создания поста'),
        ),
    ]
